/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResumeOptimizerRouteImport } from './routes/resume-optimizer'
import { Route as MyResultsRouteImport } from './routes/my-results'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InterviewCoachRouteImport } from './routes/interview-coach'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CareerTestRouteImport } from './routes/career-test'
import { Route as IndexRouteImport } from './routes/index'

const ResumeOptimizerRoute = ResumeOptimizerRouteImport.update({
  id: '/resume-optimizer',
  path: '/resume-optimizer',
  getParentRoute: () => rootRouteImport,
} as any)
const MyResultsRoute = MyResultsRouteImport.update({
  id: '/my-results',
  path: '/my-results',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewCoachRoute = InterviewCoachRouteImport.update({
  id: '/interview-coach',
  path: '/interview-coach',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerTestRoute = CareerTestRouteImport.update({
  id: '/career-test',
  path: '/career-test',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/career-test': typeof CareerTestRoute
  '/dashboard': typeof DashboardRoute
  '/interview-coach': typeof InterviewCoachRoute
  '/login': typeof LoginRoute
  '/my-results': typeof MyResultsRoute
  '/resume-optimizer': typeof ResumeOptimizerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/career-test': typeof CareerTestRoute
  '/dashboard': typeof DashboardRoute
  '/interview-coach': typeof InterviewCoachRoute
  '/login': typeof LoginRoute
  '/my-results': typeof MyResultsRoute
  '/resume-optimizer': typeof ResumeOptimizerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/career-test': typeof CareerTestRoute
  '/dashboard': typeof DashboardRoute
  '/interview-coach': typeof InterviewCoachRoute
  '/login': typeof LoginRoute
  '/my-results': typeof MyResultsRoute
  '/resume-optimizer': typeof ResumeOptimizerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/career-test'
    | '/dashboard'
    | '/interview-coach'
    | '/login'
    | '/my-results'
    | '/resume-optimizer'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/career-test'
    | '/dashboard'
    | '/interview-coach'
    | '/login'
    | '/my-results'
    | '/resume-optimizer'
  id:
    | '__root__'
    | '/'
    | '/career-test'
    | '/dashboard'
    | '/interview-coach'
    | '/login'
    | '/my-results'
    | '/resume-optimizer'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CareerTestRoute: typeof CareerTestRoute
  DashboardRoute: typeof DashboardRoute
  InterviewCoachRoute: typeof InterviewCoachRoute
  LoginRoute: typeof LoginRoute
  MyResultsRoute: typeof MyResultsRoute
  ResumeOptimizerRoute: typeof ResumeOptimizerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/resume-optimizer': {
      id: '/resume-optimizer'
      path: '/resume-optimizer'
      fullPath: '/resume-optimizer'
      preLoaderRoute: typeof ResumeOptimizerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-results': {
      id: '/my-results'
      path: '/my-results'
      fullPath: '/my-results'
      preLoaderRoute: typeof MyResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview-coach': {
      id: '/interview-coach'
      path: '/interview-coach'
      fullPath: '/interview-coach'
      preLoaderRoute: typeof InterviewCoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career-test': {
      id: '/career-test'
      path: '/career-test'
      fullPath: '/career-test'
      preLoaderRoute: typeof CareerTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CareerTestRoute: CareerTestRoute,
  DashboardRoute: DashboardRoute,
  InterviewCoachRoute: InterviewCoachRoute,
  LoginRoute: LoginRoute,
  MyResultsRoute: MyResultsRoute,
  ResumeOptimizerRoute: ResumeOptimizerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
